add_friend/urls.py
from django.conf.urls import url
from .views import index, add_new_friend

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_new_friend/$',add_new_friend, name='add_new_friend'),
]

dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

halaman_profile/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

konekin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import dashboard.urls as dashboard
import add_friend.urls as add_friend
import halaman_profile.urls as halaman_profile
import update_status.urls as update_status

urlpatterns = [
    url(r'^$', RedirectView.as_view(permanent=True, url='/update-status/'), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^stats/', include(dashboard, namespace='dashboard')),
    url(r'^add-friend/',include(add_friend, namespace ='add-friend')),
    url(r'^halaman-profil/',include(halaman_profile, namespace='halaman_profile')),
    url(r'^update-status/',include(update_status, namespace ='update-status')),
]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_status

urlpatterns = [
        url(r'^$', index, name='index'),
        url(r'^update-status', add_status, name='add-status'),
     
]

add_friend/models.py
# from django.db import models
# from django.utils import timezone

# # Create your models here.
# class Friend_List(models.Model):
#     name = models.CharField(max_length = 27)
#     email = models.EmailField()
#     created_date = models.DateTimeField(auto_now_add = True)

    

dashboard/models.py
from django.db import models

# Create your models here.

halaman_profile/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

class User(models.Model):
    name = models.CharField(max_length=27)
    birthday = models.DateField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    expertise = models.ManyToManyField('UserExpertise')
    friend = models.ManyToManyField('UserFriend')
    description = models.TextField()
    email = models.EmailField(unique=True, db_index=True)

    def __str__(self):
        return self.name

class UserProfile(models.Model):
    user = models.ForeignKey('User')
    photo = models.ImageField('profile picture', upload_to='static/media/images/avatars/',
                                       null=True, blank=True, default="static/img/noprofile.svg")

    def __str__(self):
        return self.user.name

class UserPost(models.Model):
    user = models.ForeignKey('User')
    post = models.TextField(max_length=140)
    date = models.DateTimeField()

    def __str__(self):
        return self.user.name + " " + str(self.date)

class UserExpertise(models.Model):
    expertise = models.CharField(max_length=200)

    def __str__(self):
        return str(self.expertise)

class UserFriend(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField()
    date= models.DateTimeField(auto_now_add = True)

add_friend/forms.py
from django import forms

class Add_Friend_Form(forms.Form):
    error_messages={
        'required' :'Tolong isi input ini',
    }
    attrs = {
        'class' : 'form-control'
    }

    name = forms.CharField(label= 'NAME', required = True, max_length = 28, widget = forms.TextInput(attrs=attrs))
    url = forms.URLField(label = 'URL',required = True, widget = forms.URLInput(attrs=attrs))

update_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    description_attrs = {
        'type': 'text',
        'cols': 45,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':"what's new?"
    }
    description = forms.CharField(label="", required=True, max_length=140, widget=forms.Textarea(attrs=description_attrs))

add_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Add_Friend_Form
#from .models import Friend_List
from main.models import *
from main.views import id_user_main

# Create your views here.
current_user = User.objects.get(id = id_user_main)
response = {}

def index(request):
    response['add_friend'] = Add_Friend_Form
    friends = UserFriend.objects.all()
    response['friend_list'] = friends
    html = 'add_friend/add_friend.html'
    return render(request, html, response)


def add_new_friend(request):
    form = Add_Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']        
        new_user_friend = UserFriend(name = response['name'],url = response['url'])
        new_user_friend.save()
        current_user.friend.add(new_user_friend)
        return HttpResponseRedirect('/add-friend/')
    else:
        return HttpResponseRedirect('/add-friend/')

dashboard/views.py
from django.shortcuts import render
from main.models import *
from main.views import id_user_main

response = {}

def index(request):
    response['username'] = User.objects.first().name
    response['number_of_friends'] = UserFriend.objects.count()
    response['number_of_feeds'] = UserPost.objects.count()
    response['photo_path'] = UserProfile.objects.first().photo.url[7:]
    response['user_post'] = list(reversed(UserPost.objects.filter(user_id=id_user_main)))[0]
    response['title'] = "Konekin - Stats"
    return render(request, 'dashboard.html', response)

halaman_profile/views.py
from django.shortcuts import render
from main.models import *
from main.views import id_user_main
from django.shortcuts import get_object_or_404
# Create your views here.

response = {}
user = get_object_or_404(User, id=id_user_main)
original_photo_path = UserProfile.objects.get(user_id=id_user_main).photo.url
photo_path = original_photo_path[7:]

def index(request):

    response['profile_pic'] = photo_path
    response['name'] = user.name
    response['birthday'] = user.birthday
    response['gender'] = user.get_gender_display()
    response['expertise'] = user.expertise.all()
    response['description'] = user.description
    response['email'] = user.email
    response['title'] = "Konekin - Profile"

    html = "profile.html"

    return render(request, html, response)

main/views.py
from django.shortcuts import render

id_user_main = 1

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from main.models import *
from main.views import id_user_main
from .forms import Status_Form
from django.shortcuts import render
from django.shortcuts import get_object_or_404
import datetime
# Create your views here.


response={}
user = get_object_or_404(User, id=id_user_main)
username = user.name
new_user = User.objects.get(id=id_user_main)
now = datetime.datetime.now()
#post_set = UserPost.objects.filter(user_id=id_user_main)
postingan =UserPost.objects.all().values()
original_photo_path = UserProfile.objects.get(user_id=id_user_main).photo.url
photo_path = original_photo_path[7:]


def index(request):
    post_set = UserPost.objects.filter(user_id=id_user_main)
    reversed_post = list(post_set)
    response['username'] = username
    response['photo_path'] = photo_path
    response['user_post'] = post_set
    response['title'] = "Konekin - Update Status"
    response['upstatus_form'] = Status_Form
    return render(request, 'update-status.html', response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['description'] = request.POST['description']
        todo = UserPost(user = new_user, post = response['description'], date=now)
        todo.save()
        return HttpResponseRedirect('/update-status/')
    else:
        return HttpResponseRedirect('/update-status/')

add_friend/templates/add_friend/add_friend.html
{% extends "base.html" %} {% load staticfiles %} {% load static %} {% block content %}

<section name="add-new-friend" id="add-new-friend"></section>
<div class="container">
    <div id="add-friend-title">
        <h2>Add Friend</h2>
        <hr style="height:2px;border-width:0;background-color:gray">
    </div>
    <form id="form_friend" method="POST" action="{% url 'add-friend:add_new_friend' %}">
        {% csrf_token %} {{ add_friend }}
        <br>
        <button id="btn" type="submit" class="btn btn-default">Add Friend</button>
    </form>
</div>
</section>
<br>
<section name="my-friend-list" id="my-friend-list">
    <div class="container">
        <div id="list-friend-title">
            <h2>Friend List</h2>
            <hr style="height:2px;border-width:0;background-color:gray">
        </div>
        <div class="flex">
            {% if friend_list %}
            {% for i in friend_list %}
            <div class="flex-item">
                <div class="friend-list">
                    <div class="friend-pic">
                        <img class="img-circle" src="../../static/img/K.png">
                    </div>
                    <div class="friend-name">
                        {{i.name}}
                    </div>
                    <div class="friend-url">
                        <a href="{{i.url}}">{{ i.url }} </a>
                    </div>
                    <div class="friend-added">
                        <i>Added {{ i.date }}</i>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Anda belum memiliki teman</strong> silahkan menambahkan teman baru.
            </div>
            {% endif %}
        </div>
</section>

{% endblock %}

dashboard/templates/dashboard.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
<div class="container">
    <div id="page-title-div">
            <div class="row">
                <div class="col-sm-9">
                    <h1>Statistic</h1>
                </div>
                <div id="switch-theme-area">
                    <div class="col-sm-3">
                    <label class="switch">
                      <input type="checkbox" id="switch-button">
                      <span class="slider"></span>
                    </label>
                </div>
                </div>
            </div>
    </div>
    <figure class="profile-area">
        <div class="profile-image">
            <img id="img-profile" src="{% static photo_path %}" alt="profile-img">
        </div>
        <figcaption>
        <h3 id="user-name">{{ username }}</h3>
        </figcaption>
    </figure>
    <div id="stats-card-area">
        <figure class="stats-card" >
                  <figcaption><i class="fa fa-address-book-o" aria-hidden="true"></i>
                    <h3>Friends</h3>
                    <p>{{ number_of_friends }} People</p>
                  </figcaption>
                </figure>
        <figure class="stats-card">
              <figcaption><i class="fa fa-rss" aria-hidden="true"></i>
                <h3>Feeds</h3>
                <p>{{ number_of_feeds }} Post</p>
              </figcaption>
            </figure>
    </div>
</div>
    <div id="post-area">
        <h2 id="latest-post-title">Latest Post</h2>
            {% if user_post %}
                <div class="post-container">
                      <div>
                          <div class="post-header">
                        <div class="post-author--no-cover">
                            <img id="img-profile-post-area" src="{% static photo_path %}" alt="profile-img">
                            <h3>{{ username }}</h3>
                        </div>
                      </div>

                      <div class="post-body">
                        <div class="post-summary">
                          <p>{{ user_post.post }}</p>
                        </div>
                      </div>

                      <div class="post-footer">
                        <ul>
                          <li class="published-date">{{ user_post.date }}</li>
                        </ul>
                      </div>
                      </div>
                    </div>
            {% else %}
                <div class="alert alert-danger text-center">
                    <strong>No Status In Database!</strong>
                </div>
            {% endif %}
    </div>
{% endblock %}

halaman_profile/templates/profile.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
    <body>
    <link rel="stylesheet" href="{% static 'profile.css' %}">

    <div class="title">
        <h1> PROFILE PAGE </h1>
    </div>
    <div class="circle1"></div>

    <div class="profile_picture">
        <img id="img-profile" src="{% static profile_pic %}" alt="profile-img" class="center">
    </div>

    <div class="container">

        <div id="name">
            {{ name }}
        </div>

        <div id="bio">
            <table align="center">
                <tr>
                    <td id="subject">Birthday</td>
                    <td id="value">{{ birthday }}</td>
                </tr>
                <tr>
                    <td id="subject">Gender</td>
                    <td id="value">{{ gender }}</td>
                </tr>
                <tr>
                    <td id="subject">Expertise</td>
                    <td id="value">{% for obj in expertise %}
                        <div class = "expertise">{{ obj }}</div>
                    {% endfor %}</td>
                </tr>
                <tr>
                    <td id="subject">Description</td>
                    <td id="value">{{ description }}</td>
                </tr>
                <tr>
                    <td id="subject">Email</td>
                    <td id="value">{{ email }}</td>
                </tr>
            </table>
        </div>
    </div>
    </body>

{% endblock %}

templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {# variabel title custom untuk setiap app, usahakan return dari fungsi index #}
    <title>
        {% block title %} {{ title }}{% endblock %}
    </title>
    <meta name="Description" content="Konekin - Tugas 1 Kelompok 10 Kelas B Tahun 2017">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/add_friend.css' %}"/>

    <link href=' http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link href=' http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <link rel="shortcut icon" type="image/png" href={% static 'img/konekin.ico' %}/>
</head>
<header>
    {% include "partials/header.html" %}
</header>
<body oncontextmenu="return false;"> <!--edit-->
<content>
    {% block content %}
        <!-- content goes here -->
    {% endblock %}
</content>

</body>
<footer>
    {% block footer %}
        {% include "partials/footer.html" %}
    {% endblock %}
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript"
        src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="application/javascript">
    {# jika ingin nambahin script js disini letakkan kodenya #}
    $('#switch-button').click(function() {
      if ($(this).is(':checked')) {
        $('body').css({
            'background-color': 'white'
        });
      } else {
        $('body').css({
            'background-color': '#DEF2F1'
        });
      }
    });
</script>

templates/partials/footer.html
<div class="footer">
  <p>&copy; Konekin 2017</p>
</div>

templates/partials/header.html
{# Project Navbar Konekin#}
<nav class="navbar navbar-default navbar-fixed-top sticky" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">KONEKIN</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav" style="float: right" id="navbar-right-menu" >
        <li><a href="/update-status">Status</a></li>
        <li><a href="/halaman-profil">Profile</a> </li>
        <li><a href="/add-friend">Friends</a></li>
        <li><a href="/stats">Stats</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

update_status/templates/update-status.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<style>
@media only screen and (max-width: 768px) {
  #input-list form {
      width: 290px;
  }
  .to-do-list .to-do-list-delete {
    bottom: -50px;
  }
  .flex-item .flex-container{
    padding: 0 15px;
    flex-grow: 0;
    flex-shrink: 0;
    flex-basis: 100%;
  }
    }
.flex-container {

  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  text-align: center;
  background: #3AAFA9;
  position: relative;
  align-items: flex-start;
  align-content: flex-start;
  margin-right: -15px;
  margin-left: -15px;

}
#input-list form{
  width: 400px;
  margin: 50px auto;
  text-align: center;
  position: relative;
  z-index: 1;
  background: white;
  border: 0 none;
  border-radius: 3px;
  box-shadow: 0 0 15px 1px rgba(0, 0, 0, 0.4);
  padding: 20px 30px;
  box-sizing: border-box;
  position: relative;
}

.flex-item {
    background-color: cornflowerblue;
    width: 100px;
    height: 100px;
    margin: 10px;
}
</style>


<h1 class="container">Update Status</h1>
<hr/>
<section name="input-list" id="input-list">
    <center>
    <div class="flex-container" >
        <form id="form" method="POST" action="{% url 'update-status:add-status' %}">
            <h2>What's New?</h2>
            {% csrf_token %}
            {{ upstatus_form }}
            <br>
            <br>
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit" maxlength="280" minlength="180">
            <br>
        </form>

    </div>
    </center>
</section>
<div class="container">
<section name="my-list" id="my-list">
    <div class="container" >
        <h2 class="my-list-title">My Status</h2>
        <div class="flex">
            {% if user_post %}
            {% for data in user_post reversed %}
                <div class="post-container">
                  <div>
                      <div class="post-header">
                    <div class="post-author--no-cover">
                        <img id="img-profile-post-area" src="{% static photo_path %}" alt="profile-img">
                        <h3>{{ username }}</h3>
                    </div>
                  </div>

                  <div class="post-body">
                    <div class="post-summary">
                      <p>{{ data.post }}</p>
                    </div>
                  </div>

                  <div class="post-footer">
                    <ul>
                      <li class="published-date">{{ data.date }}</li>
                    </ul>
                  </div>
                  </div>
                </div>
            {% endfor %}
             {% else %}
            <div class="alert alert-danger text-center">
                <strong>No Status!</strong>
            </div>
            {% endif %}
        </div>
    </div>
</section>
</div>

{% endblock %}        

update_status/templates/update-status/update-status.html
{% extends "base.html" %}
{% block content %}

<style type="text/css">
@import url(https://fonts.googleapis.com/css?family=Open+Sans:200);
@import url(https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css);
.snip1578 {
  font-family: 'Open Sans', Arial, sans-serif;
  position: relative;
  display: inline-block;
  margin: 40px 8px;
  min-width: 280px;
  max-width: 380px;
  width: 100%;
  color: #000;
  text-align: left;
  font-size: 16px;
  background: #E8F7F3;
  box-shadows: 5px 5px
  border-radius: 5px;
}

.snip1578 *,
.snip1578:before,
.snip1578:after {
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
  -webkit-transition: all 0.4s ease;
  transition: all 0.4s ease;
}

.snip1578 img {
  max-width: 35%;
  margin-top: -15px;
  margin-left: 60%;
  margin-bottom: 15px;
  backface-visibility: hidden;
  vertical-align: top;
  border-radius: 5px;
}

.snip1578 figcaption {
  position: absolute;
  top: 0;
  right: 40%;
  left: 0;
  bottom: 0;
  padding: 15px;
}

.snip1578 h4 {
  margin: 0;
  font-size: 1.1em;
  font-weight: normal;
}

.snip1578 h6 {
  margin: 0;
  color: grey;
}

.snip1578 .icons {
  font-size: 1.6rem;
}

.snip1578 .icons a {
  color: #ccc;
}

.snip1578 .icons a:hover {
  color: #2980b9;
}


/* Demo purposes only */

body {
  text-align: center;
}
</style>
<h1 class="main-title">Update Status</h1>
<hr/>
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'update-status:add-status' %}">
            <h2>What's New?</h2>

            {% csrf_token %}
            {{ upstatus_form }}

            <br>
            <br>
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit" maxlength="280" minlength="180">
            <br>
        </form>
    </div>
</section>
<section name="my-list" id="my-list">
    <div class="container" >
        <h2 class="my-list-title">My Status</h2>
        <div class="flex">
            {% if upstatus %}
                {% for data in upstatus reversed %}
            <figure class="snip1578" >
              <img src="https://sucifadhilah.files.wordpress.com/2011/08/fasilkom.png"/>
              <figcaption>
                   <h4>
                    <div class="to-do-list-description">
                        {{data.description}}
                    </div>
                </h4>
                  <h6>
                  <div class="to-do-list-date-added">
                      {{data.created_date}}
                  </div>
                  </h6>
                <div class="icons"><a href="#"><i class="ion-social-twitter"></i></a>
                  <a href="#"> <i class="ion-social-instagram-outline"></i></a>
                  <a href="#"> <i class="ion-social-github"></i></a>
                </div>
              </figcaption>
            </figure>
            <br>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>No Status!</strong>
            </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}        